version: "3.3"
volumes:
    postgres-data:
    pgadmin-data2:

services:
    postgres:
        build:
            context: ./postgres
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
          - bots
            
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:6.10
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: moein.fatehi@gmail.com
            PGADMIN_DEFAULT_PASSWORD: pgadminpass
        ports:
            - "8765:80"
        volumes:
            - pgadmin-data2:/var/lib/pgadmin
        networks:
          - bots
    app:
        container_name: app
        build:
          context: ./app/
        tty: true
        volumes:
          - ./app:/app
        networks:
          - bots

networks:
  bots:
    name: bots
    driver: bridge
    ipam:
        config:
           - subnet: 172.16.57.0/24